### ISSUE TITLE
stl -backend fails when rerunning

### ISSUE THREAD

**Issue by ebknudsen** [openmsr/CAD_to_OpenMC#47]
The stl-backend has a problem when being run more than once from the same script invocation.
It tends to crash with an error message like:

Traceback (most recent call last):
  File "/data/erkn/lost_particles/meshsphere.py", line 12, in <module>
    a.run(h5m_filename=str(h5mf))
  File "/home/erkn/o2mc/lib/python3.9/site-packages/CAD_to_OpenMC/assembly.py", line 143, in run
    self.solids_to_h5m(backend=backend,h5m_filename=h5m_filename)
  File "/home/erkn/o2mc/lib/python3.9/site-packages/CAD_to_OpenMC/assembly.py", line 372, in solids_to_h5m
    stl_list=meshgen.generate_stls()
  File "/home/erkn/o2mc/lib/python3.9/site-packages/CAD_to_OpenMC/assemblymesher_cq.py", line 62, in generate_stls
    self._mesh_surfaces()
  File "/home/erkn/o2mc/lib/python3.9/site-packages/CAD_to_OpenMC/assemblymesher_cq.py", line 132, in _mesh_surfaces
    merge_stl(str(cwd / volname), volumefaces,of='bin')
  File "/home/erkn/o2mc/lib/python3.9/site-packages/CAD_to_OpenMC/stl_utils.py", line 17, in merge_stl
    infp=open(s,"rb")
FileNotFoundError: [Errno 2] No such file or directory: 'vol_1_face0.stl'

This is likely caused by the face-hash table being persistent past invocations. It is a class-variable.

**Comment by ebknudsen** [comment]
Fixed by fc81b8c
